import React from 'react';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { WEBSITE_DEV_SOLUTIONS_DATA } from '@/data/websiteDevSolutions';
import DetailLayout from '@/components/WebsiteDevServiceDetail/DetailLayout';

// Get all Website Development slugs for static generation
export async function generateStaticParams() {
    // List of slugs that have their own hardcoded directories/pages
    // These should NOT be generated by this dynamic route
    const hardcodedSlugs = [
        'cms-website-development',
        'corporate-website-development',
        'dynamic-website-development',
        'php-website-development',
        'shopify-website-development',
        'static-website-development',
        'travel-website-development',
        'website-re-development'
    ];

    const webDevSlugs = Object.keys(WEBSITE_DEV_SOLUTIONS_DATA).filter(
        slug =>
            WEBSITE_DEV_SOLUTIONS_DATA[slug].category === 'WebsiteDevelopment' &&
            !hardcodedSlugs.includes(slug)
    );

    // Debug logging for build time
    console.log(`Generating params for ${webDevSlugs.length} dynamic Website Development pages (excluding hardcoded):`, webDevSlugs);

    return webDevSlugs.map(slug => ({ slug }));
}

// Dynamic metadata
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
    const { slug } = await params;
    const service = WEBSITE_DEV_SOLUTIONS_DATA[slug];

    if (!service || service.category !== 'WebsiteDevelopment') {
        return { title: 'Service Not Found' };
    }

    return {
        title: `${service.title} | Prism Infoways`,
        description: service.description.replace(/<[^>]*>?/gm, '').substring(0, 160),
    };
}

const Page = async ({ params }: { params: Promise<{ slug: string }> }) => {
    const { slug } = await params;
    const service = WEBSITE_DEV_SOLUTIONS_DATA[slug];

    // Only allow Website Development category services
    if (!service || service.category !== 'WebsiteDevelopment') {
        notFound();
    }

    return <DetailLayout service={service} />;
};

export default Page;
